### ISSUE TITLE
making it easier to update meson native projects

### ISSUE THREAD

**Issue by noah1510** [mesonbuild/wrapdb#1022]
At the moment all wrap files need to be in wrap-file format.
This makes them more annoying to update since all fields have to be updated for every new release manually.

~For projects that are already using meson by default, it would be better to allow them to use the wrap-git format.
This means that for a new release only the revision has to change and the new version has to be added to the json file.
Can this be done, if not what are the reasons for that and can that information be added to the readme?
At the moment the readme does not specify that the new wrap file has to be in wrap-file format.~

For technical reasons that does not seem possible.
The main reason for this issue was finding an easier solution for updating the wrap db packages.
Possible solutions and reasons for/against and steps that can be taken:

- ~allow wrap-git format~ has a lot of problems look at the comments for details
  - [ ] Add a note in the documentation (e.g. Readme)  that only the wrap-file format is allowed
- Have a github/gitlab CI function that makes it easy to update wrapdb from the ci
  - [X] Create a script that can update the wrap and release file from a git tag
  - [X] Commit and push those changes to a new branch of a wrapdb fork
  - [ ] Add various sanity checks to ensure the new data is valid
    - [X] Check if the tag and repos actually exist
    - [x] Check if the version is newer than the other version (not sure if needed)
    - [ ] Run the sanity checks (See noah1510/update-wrapdb-action#1 for details) 
  - [ ] Create a PR from that branch to the main repository
- Have something like the arduino library update bot that checks registered repos for new releases
  - [ ] have a list of repositories to keep track of
  - [ ] run the actions update script for those repos in a fixed interval

**Comment by eli-schwartz** [comment]
Wrap-file has a few advantages:
- it works correctly when included in another project's tarball releases, when git isn't installed on the build machine
- it is more secure, since it can be verified with a checksum
- installing a new version of a wrap will force meson to fetch the updated version, since the cache key is the directory name -- and tarballs typically contain a version in the top-level directory, but git repos don't have the version in the directory name

**Comment by tp-m** [comment]
In GStreamer we have been actively moving away from git wraps to tarball wraps because otherwise every third party gitlab/github infrastructure issue brings down our CI, but it's also easier to update/cache, and fallback urls can be provided.

**Comment by noah1510** [comment]
> otherwise every third party gitlab/github infrastructure issue brings down our CI

Isn't that the same for the wrap-file format? If the servers are down you cannot download the archive.
Also isn't it possible to add fallback URLs to the wrap-git format? In theory you could have a secondary upstream repository that meson will fallback to, in case the main repo does not work. Git has all the feature needed for that already, although they are a bit messy.

**Comment by xclaesse** [comment]
One thing I've been wanting for a while is to be able to have both wrap-file and wrap-git in the same file. When I'm a developer of the subprojects I want to have it from git. But build bots are probably better with tarballs.

Even better is if meson could somehow find existing git repo in a configured place and use a worktree instead of cloning.

Finally, and more to the point of the actual issue here, wrap file format is inconsistent with cross file format which supports concat strings, etc. That would allow in most cases to have the version in `[constants]` section and build url and directory fields from it.

**Comment by xclaesse** [comment]
> Isn't that the same for the wrap-file format? If the servers are down you cannot download the archive

Technically we could have fallback url for git, afterall that's the whole point of it being distributed. In practice it's easier to do with tarballs, and wrapdb already automatically backup tarballs on GitHub and set fallback url in the wrap which solves the problem with less stable hosts services.

**Comment by eli-schwartz** [comment]
> After updating the wrap file most of the time I have to reconfigure the project unless the subproject is using wrap-git which seems to be more reliable when it comes to reporting source changes.

Updating a wrap-git will effectively start from scratch, which makes sense if you think of it similar to upgrading a package (linux distro dependencies, conan, etc.)

> Basically the third point is a mostly an implementation limitation that may be better in the future, or am I misunderstanding something? If a cache key is needed the git sha or revision can be used to see if the subproject needs an update. The submodule update command seems to work just fine if the wrap file is set just track a branch.

Checking whether the revision matches is more complicated than verifying whether the wrap-git cache key matches. And you actually cannot prove that a git repository is up to date with its revision specifier unless it uses commit sha1s. Both branches and tags are moving targets. But commit sha1s are unfriendly in terms of checking that they refer to a stable tagged release.

> Isn't that the same for the wrap-file format? If the servers are down you cannot download the archive.
> Also isn't it possible to add fallback URLs to the wrap-git format? In theory you could have a secondary upstream repository that meson will fallback to, in case the main repo does not work. Git has all the feature needed for that already, although they are a bit messy.

Well, tarballs can be trivially mirrored -- git repositories are more complicated, you cannot do it by uploading to github releases as the WrapDB itself does. It also makes security issues much worse -- because now you have NO way to know that a revision using a tag is truthful, whereas using the original clone url gives you a bit of protection in that only the authorized users are expected to be able to update it. The WrapDB isn't an authorized user for post-modifying your `*.wrap`s and having them refer to different code than they referred to at the time you installed the wrap file.

**Comment by noah1510** [comment]
I understand that allowing wrap-git might not be the best idea for technical reasons.
Could a note be added to the documentation somewhere to help devs that are new to meson and the wrap system?

Despite all of this I still think there should be a simpler way to update wrapdb packages which use a public git repo and are native meson projects.
For example Arduino solved this by having a bot that scans all registered repositories for new releases and automatically updates their library manager once a new release is found.
Would something similar be possible for the wrap db?
Having the devs manually create a pull request for every update seems like more overhead than needed and can result in many missed updates which can be prevented by simple automation.

**Comment by jpakkane** [comment]
> Would something similar be possible for the wrap db?

Sure, but it would require someone to implement and maintain that program. Sadly most of us are already overworked.

I guess we'd also need a server to automatically run that and then submit pull requests, though I guess someone could run it once a week on their own machine or something.

**Comment by noah1510** [comment]
Well that makes sense.
Sadly I don't have the knowledge to build that myself.

For now I will look into creating a github composite action, which creates a pull request with the new release.

**Comment by noah1510** [comment]
I have created an action that can automatically update the release json file and the wrap file from a given git repo and tag.
It also commits and pushes these changes to a fork of the wrapdb.
For now the only manual part is creating the pr.
Documentation is missing atm, but I will add the minimum needed today.
You can find the action here: https://github.com/noah1510/update-wrapdb-action

Could somebody help test this action across more projects?
The python script that does most of the work (update_repo.py) can be executed manually so feel free to it instead of the action.
Once some more testing is done, I will publish the action to the marketplace and add the automatic creation of the pr.

**Comment by noah1510** [comment]
After some testing the update action seems to work more or less.
I just created #1048 with the commit created by the action.
The action still does not open a pr automatically but that will be added once I tag the script with v1.

At the moment the sanity checks are not run by the scripts.
Is there a way to use the sanity checks from a python file?
I think that would be the best way to integrate them in the update process.

**Comment by bgilbert** [comment]
As of  #1555, the repo now includes [`versions.py`](https://github.com/mesonbuild/wrapdb/blob/master/tools/versions.py), which can generate a report of all wrap versions, plus their corresponding upstream versions for those projects known to [release-monitoring.org](https://release-monitoring.org/).  It can also generate automatic wrap updates for those projects that use Meson upstream.

Twice a week, [this repository](https://github.com/wrapdb-bot/autoupdate) runs a [GitHub Actions workflow](https://github.com/wrapdb-bot/autoupdate/blob/main/.github/workflows/autoupdate.yml) that uses `versions.py` to generate automated PRs (for example #1638) and submits them to WrapDB.  (The number of PRs created per run is currently rate-limited, but that limit will eventually be lifted.)  It doesn't sanity-check the PRs itself, and instead relies on WrapDB's CI to check them.

I think this functionality meets the needs covered here?

**Comment by jpakkane** [comment]
Thank you very much for working on this.

**Comment by bgilbert** [comment]
Is there any value in having the bot maintain an open issue that lists wraps needing manual updates?

**Comment by bgilbert** [comment]
Seems like this issue can be closed now.
