### ISSUE TITLE
harfbuzz wrap is not functional, and as such should be removed from wrapdb

### ISSUE THREAD

**Issue by tksuoran** [mesonbuild/wrapdb#26]
harfbuzz wrap is not functional, and as such should be removed from wrapdb

**Comment by legeana** [comment]
Same problem, https://github.com/mesonbuild/mesonwrap/issues/130

**Comment by jpakkane** [comment]
In general when upstream adds their own Meson files, the reasonable thing to do is:

- Keep the current version as is.
- Wait for a release with the new stuff
- Import the new release to wrapdb with no added files

Since upstream does things differently, things _might_ break but it will only happen when users explicitly update their versions. Old versions keep on working without any changes.
