### ISSUE TITLE
new wrap: libtiff

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#40]
upstream link: https://gitlab.com/libtiff/libtiff/-/archive/v4.1.0/libtiff-v4.1.0.zip
version: 4.1.0

**Comment by legeana** [comment]
From what I found in wikipedia the homepage is http://simplesystems.org/libtiff/.
I would really appreciate if you provided homepage in the request itself instead of the source code :)

$ mesonwrap new_repo --homepage=http://simplesystems.org/libtiff --version=4.1.0 --directory=~/wrapdb/libtiff libtiff
Repository created: https://github.com/mesonbuild/libtiff
