### ISSUE TITLE
new wrap: mpdecimal

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/wrapdb#79]
upstream url: http://www.bytereef.org/mpdecimal/index.html
version: 2.5.0

The project name is mpdecimal but it installs two libraries: `libmpdec` and `libmpdec++`. The autoconf based original build system does not install a `pkg-config`. I think the right thing to do is to have a `mpdecimal` wrap exporting two dependencies: `libmpdec_dep` and `libmpdecpp_dep`.

**Comment by jpakkane** [comment]
And the dependency names would be `mpdec` and `mpdecpp`?

**Comment by dnicolodi** [comment]
I was thinking `libmpdec` and `libmpdec++` (assuming the latter is a valid dependency name) but I don't know if it is more common to have or not the `lib` suffix in the dependency name. I am open to proposals.

**Comment by jpakkane** [comment]
It's usually wise to avoid special characters, they tend to break things unexpectedly.

Whether the dependency name should have a lib prefix or not is quite arbitrary. Some libs have it while others don't. I personally prefer not to have it because it because the dependencies already are libraries. Saying it again with the prefix is redundant.

**Comment by jpakkane** [comment]
Anyhow, repo created.

**Comment by dnicolodi** [comment]
Thank you (also for merging the `reflex` PR).
