### ISSUE TITLE
internal dependencies woes

### ISSUE THREAD

**Issue by benoit-pierre** [mesonbuild/wrapdb#913]
What's the policy for wraps that don't work when some of their dependencies come from internal dependencies (other subprojects), should the checks be relaxed?

For example `libarchive` checks for `libacl`, `zlib`, `ZSTD` break if those are provided by subprojects, and could be changed to:

```diff
@@ -214,6 +214,7 @@ endif
 zlib_dep = dependency('zlib', disabler: true, required: get_option('zlib'))
 if zlib_dep.found()
   cdata.set('HAVE_LIBZ', 1)
+  cdata.set('HAVE_ZLIB_H', 1)
   deps += zlib_dep
 endif

@@ -238,8 +239,9 @@ endif
 zstd_dep = dependency('libzstd', disabler: true, required: get_option('zstd'))
 if zstd_dep.found()
   cdata.set('HAVE_LIBZSTD', 1)
+  cdata.set('HAVE_ZSTD_H', 1)
   deps += zstd_dep
-  if cc.has_function('ZSTD_compressStream', dependencies: zstd_dep)
+  if zstd_dep.version().version_compare('>=0.7.5')
     cdata.set('HAVE_LIBZSTD_COMPRESSOR', 1)
   endif
 endif
@@ -293,7 +295,11 @@ iconv_const_test = '''

 if iconv_dep.found()
   cdata.set('HAVE_ICONV', 1)
+  cdata.set('HAVE_ICONV_H', 1)
   cdata.set('ICONV_CONST', cc.compiles(iconv_const_test, dependencies: iconv_dep) ? 'const' : '')
+  if cc.has_header_symbol('iconv.h', 'locale_charset', dependencies: iconv_dep.partial_dependency(compile_args: true, includes: true
+    cdata.set('HAVE_LOCALE_CHARSET', 1)
+  endif
   deps += iconv_dep
 else
   cdata.set('ICONV_CONST', cc.compiles(iconv_const_test) ? 'const' : '')
@@ -313,15 +319,22 @@ endif
 libacl_dep = dependency('libacl', disabler: true, required: get_option('acl'))
 if libacl_dep.found()
   cdata.set('HAVE_LIBACL', 1)
+  cdata.set('HAVE_ACL_LIBACL_H', 1)
   cdata.set('ARCHIVE_ACL_LIBACL', 1)
+  if libacl_dep.version().version_compare('>=2.0.15')
+    cdata.set('HAVE_ACL_CREATE_ENTRY', 1)
+    cdata.set('HAVE_ACL_GET_PERM', 1)
+    cdata.set('HAVE_ACL_INIT', 1)
+    cdata.set('HAVE_ACL_SET_FD', 1)
+    cdata.set('HAVE_ACL_SET_FILE', 1)
+  endif
   deps += libacl_dep
 endif

[…]
```

**Comment by neheb** [comment]
oh so you're saying --wrap_mode=forcefallback fails?

**Comment by benoit-pierre** [comment]
Yes.

**Comment by neheb** [comment]
your posted snippet seems sane.

I'll also note the wrap cold use a lot of improvement. When I wrote it I mostly looked at how similar it was to the cmake config file. There's a lot of missing stuff,

**Comment by eli-schwartz** [comment]
> What's the policy for wraps that don't work when some of their dependencies come from internal dependencies (other subprojects), should the checks be relaxed?

In general, yes, because the underlying issue is that it's impossible to do a compile-check against something that hasn't yet been compiled... but compile checks are slow and inelegant, and typically mean that you're trying to detect a condition that doesn't have proper versioning.

The best example of a compile check is the case where you need to check a libc interface. The second... "best" example is where you need to check the interface of a library that doesn't have a corresponding pkg-config file providing a version.

If it's ever possible to determine that a function is available because the detected version is sufficient, then that should always be used. Version checks always work without running a compiler, and that's a huge win to configure times even if we ignore the subproject issues.

**Comment by benoit-pierre** [comment]
Makes sense, thanks.
